apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: cka
  labels:
    app: test
spec:
  containers: 
  - image: redis
    name: foo
    command: ["sleep"]
    args: ["3600"]
  restartPolicy: Always
  nodeSelector:
   net: gigabit
  hostname: test
