apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: cka
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  restartPolicy: Always
