apiVersion: v1
kind: Pod
metadata:
  name: bumpy-llama
spec:
  volumes:
  - name: workdir
    emptyDir: {}
  containers:
  - name: checker
    image: alpine
    command: ["/bin/sh","-c","if [-f /workdir/gentle.txt]; then sleep 1000; else exit 1; fi" ]
    volumeMounts:
    - name: workdir
      mountPath: /workdir

