apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: cka
spec:
  containers:
  - image: redis
    name: container1
    command: ["sleep","60"]
  - image: redis
    name: container2
    command: ["sleep","60"]
  - image: redis
    name: container3
    command: ["sleep","60"]
  - image: redis
    name: container4
    command: ["sleep","60"]
