apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ha
  namespace: cka
  annotations:
    AppVersion: "1.1"
spec:
  selector:
    matchLabels:
      app: ha
  replicas: 3
  template:
    metadata:
      labels:
        app: ha
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
