apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env 
  namespace: cka
  labels:
    app: secret
spec:
  containers:
  - image: redis
    name: secret
    command: ["sleep","3600"]
    volumeMounts:
    - name: vol-super-secret
      mountPath: /secrets
    env:
    - name: PASS_ENV
      value: toptop
    - name: PASS_SECRET
      valueFrom:
        secretKeyRef:
          name: super-secret
          key: password 
    - name: LANGUAGUE_CONFIG_MAP
      valueFrom:     
        configMapKeyRef:
          name: app-configmap
          key: LANGUAGE
  volumes:
  - name: vol-super-secret
    secret:
      secretName: super-secret
