apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env 
  labels:
    app: secret
spec:
  containers:
  - image: redis
    name: secret
    command: ["sleep","3600"]
    volumeMounts:
    - name: vol-super-secret
      mountPath: /secrets
  volumes:
  - name: vol-super-secret
    secret:
      secretName: super-secret
