apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-03
  namespace: cka
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/pv-03
    server: 172.31.29.133
    readOnly: false

