apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-04
  namespace: cka
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/pv-04
    server: 172.31.29.133
    readOnly: false

