apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  namespace: cka
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    path: /var/nfs/pv-01
    server: 172.31.29.133
    readOnly: false

